
name: PostgreSQL execute script
run-name: PostgreSQL execute script in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
          - dev
          - test
          # - prod
      script:
        type: choice
        description: SQL script to execute
        options:
          - 01_setup_db
          - 02_assign_app_roles
          - 03_custom

permissions:
  id-token: write

env:
  WORK_DIR: ./cac/sql
  PSQL_FQDN: psql-${{ github.event.inputs.environment }}-uks-nomad-01.postgres.database.azure.com 

jobs:
  execute_sql:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Execute script ${{ github.enent.inputs.script }}
        run: |
          PRINCIPAL_NAME="id-dev-uks-nomad-tf"
          export PGPASSWORD=$(az account get-access-token --resource-type oss-rdbms --query "[accessToken]" -o tsv)
          psql -h "${{ env.PSQL_FQDN }}" -p 5432 -U "$PRINCIPAL_NAME" -d nomad -f "${{ github.event.inputs.script }}.sql"
          

