name: terraform-destroy
run-name: Terraform destroy dev instance of nomad-backend

on:
  workflow_dispatch:

env:
 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
 ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
 ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
 ARM_USE_AZUREAD: true
 work_dir: ./iac
 environment: dev
 app_name: nomad-backend

permissions:
  id-token: write
  contents: read

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.app_name }}"

      - name: Terraform destroy
        run: |
          terraform destroy -input=false \
            -var "resource_group_name=${{ vars.AZURE_RESOURCE_GROUP_NAME }}" \
            -var "environment_settings={environment=${{ env.environment }}}" \
            -var-file="tfvars/${{ env.environment }}/main.tfvars"
      
