name: deploy-nomad-infra
run-name: Terraform deploy ${{ github.event.inputs.app_name }} in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
          - dev
          - test
          # - prod
      app_name:
        type: choice
        description: Application name
        options: 
          - nomad-backend
      redeploy_vm_extension:
        type: boolean
        description: Explicitly re-deploy configure_vm.sh
      
    
env:
 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
 ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
 ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
 ARM_USE_AZUREAD: true
 work_dir: ./iac

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Terraform plan
        if: ${{ github.event.inputs.redeploy_vm_extension }}
        uses: davejg10/pipeline_templates/.github/actions/terraform_plan@v1
        with:
          backend_azure_resource_group_name: ${{ vars.backend_azure_resource_group_name }}
          backend_azure_storage_account_name: ${{ vars.backend_azure_storage_account_name }}
          backend_container_name: ${{ github.event.inputs.app_name }}
          environment: ${{ github.event.inputs.environment }}
          work_dir: ${{ env.work_dir }}
          additional_tf_vars: -var "vm_extension_replacement=${{ github.run_number }}"
      
      - name: Terraform plan
        if: ${{ github.event.inputs.redeploy_vm_extension != 'true' }}
        uses: davejg10/pipeline_templates/.github/actions/terraform_plan@v1
        with:
          backend_azure_resource_group_name: ${{ vars.backend_azure_resource_group_name }}
          backend_azure_storage_account_name: ${{ vars.backend_azure_storage_account_name }}
          backend_container_name: ${{ github.event.inputs.app_name }}
          environment: ${{ github.event.inputs.environment }}
          work_dir: ${{ env.work_dir }}
      
  terraform_apply:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    needs: terraform_plan
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Terraform apply
        uses: davejg10/pipeline_templates/.github/actions/terraform_apply@v1
        with:
          backend_azure_resource_group_name: ${{ vars.backend_azure_resource_group_name }}
          backend_azure_storage_account_name: ${{ vars.backend_azure_storage_account_name }}
          backend_container_name: ${{ github.event.inputs.app_name }}
          work_dir: ${{ env.work_dir }}